import type { ThemeMeta, VsCodeThemeRaw } from './types'

export const BUILTIN_THEMES: ThemeMeta[] = [
  { id: 'dark-modern', name: 'Dark Modern', type: 'dark', builtin: true },
  { id: 'light-modern', name: 'Light Modern', type: 'light', builtin: true },
  { id: 'dark-plus', name: 'Dark+', type: 'dark', builtin: true },
  { id: 'monokai', name: 'Monokai', type: 'dark', builtin: true },
  { id: 'solarized-dark', name: 'Solarized Dark', type: 'dark', builtin: true },
  { id: 'solarized-light', name: 'Solarized Light', type: 'light', builtin: true },
  { id: 'one-dark-pro', name: 'One Dark Pro', type: 'dark', builtin: true },
  { id: 'github-dark', name: 'GitHub Dark', type: 'dark', builtin: true },
]

const BUILTIN_RAW: Record<string, VsCodeThemeRaw> = {
  'dark-modern': {
    name: 'Dark Modern',
    type: 'dark',
    colors: {
      'editor.background': '#1f1f1f',
      'editor.foreground': '#cccccc',
      'sideBar.background': '#181818',
      'sideBar.foreground': '#cccccc',
      'sideBar.border': '#2b2b2b',
      'activityBar.background': '#181818',
      'editorGroupHeader.tabsBackground': '#181818',
      'tab.activeBackground': '#1f1f1f',
      'panel.background': '#181818',
      'list.hoverBackground': '#2a2d2e',
      'editorWidget.background': '#252526',
      'focusBorder': '#007acc',
      'button.background': '#007acc',
      'errorForeground': '#f85149',
      'terminal.ansiGreen': '#89d185',
      'descriptionForeground': '#858585',
    },
    tokenColors: [
      { scope: 'comment', settings: { foreground: '#6A9955' } },
      { scope: 'string', settings: { foreground: '#CE9178' } },
      { scope: 'keyword', settings: { foreground: '#569CD6' } },
      { scope: 'entity.name.function', settings: { foreground: '#DCDCAA' } },
      { scope: 'entity.name.type', settings: { foreground: '#4EC9B0' } },
      { scope: 'variable', settings: { foreground: '#9CDCFE' } },
      { scope: 'constant.numeric', settings: { foreground: '#B5CEA8' } },
      { scope: 'entity.name.tag', settings: { foreground: '#569CD6' } },
    ],
  },
  'light-modern': {
    name: 'Light Modern',
    type: 'light',
    colors: {
      'editor.background': '#ffffff',
      'editor.foreground': '#3b3b3b',
      'sideBar.background': '#f3f3f3',
      'sideBar.foreground': '#3b3b3b',
      'sideBar.border': '#e5e5e5',
      'activityBar.background': '#f3f3f3',
      'editorGroupHeader.tabsBackground': '#f3f3f3',
      'tab.activeBackground': '#ffffff',
      'panel.background': '#ffffff',
      'list.hoverBackground': '#e8e8e8',
      'editorWidget.background': '#f3f3f3',
      'focusBorder': '#007acc',
      'button.background': '#007acc',
      'errorForeground': '#e51400',
      'terminal.ansiGreen': '#0e8623',
      'descriptionForeground': '#6e6e6e',
    },
    tokenColors: [
      { scope: 'comment', settings: { foreground: '#008000' } },
      { scope: 'string', settings: { foreground: '#A31515' } },
      { scope: 'keyword', settings: { foreground: '#0000FF' } },
      { scope: 'entity.name.function', settings: { foreground: '#795E26' } },
      { scope: 'entity.name.type', settings: { foreground: '#267F99' } },
      { scope: 'variable', settings: { foreground: '#001080' } },
      { scope: 'constant.numeric', settings: { foreground: '#098658' } },
      { scope: 'entity.name.tag', settings: { foreground: '#800000' } },
    ],
  },
  'dark-plus': {
    name: 'Dark+',
    type: 'dark',
    colors: {
      'editor.background': '#1e1e1e',
      'editor.foreground': '#d4d4d4',
      'sideBar.background': '#252526',
      'sideBar.border': '#2d2d30',
      'editorGroupHeader.tabsBackground': '#252526',
      'tab.activeBackground': '#1e1e1e',
      'focusBorder': '#007acc',
      'button.background': '#0e639c',
      'descriptionForeground': '#858585',
    },
    tokenColors: [
      { scope: 'comment', settings: { foreground: '#6A9955' } },
      { scope: 'string', settings: { foreground: '#CE9178' } },
      { scope: 'keyword', settings: { foreground: '#569CD6' } },
      { scope: 'entity.name.function', settings: { foreground: '#DCDCAA' } },
      { scope: 'entity.name.type', settings: { foreground: '#4EC9B0' } },
    ],
  },
  'monokai': {
    name: 'Monokai',
    type: 'dark',
    colors: {
      'editor.background': '#272822',
      'editor.foreground': '#F8F8F2',
      'sideBar.background': '#1e1f1c',
      'sideBar.foreground': '#F8F8F2',
      'sideBar.border': '#3e3d32',
      'editorGroupHeader.tabsBackground': '#1e1f1c',
      'tab.activeBackground': '#272822',
      'focusBorder': '#A6E22E',
      'button.background': '#A6E22E',
      'errorForeground': '#F92672',
      'descriptionForeground': '#90908a',
    },
    tokenColors: [
      { scope: 'comment', settings: { foreground: '#75715E' } },
      { scope: 'string', settings: { foreground: '#E6DB74' } },
      { scope: 'keyword', settings: { foreground: '#F92672' } },
      { scope: 'entity.name.function', settings: { foreground: '#A6E22E' } },
      { scope: 'entity.name.type', settings: { foreground: '#66D9EF' } },
      { scope: 'variable', settings: { foreground: '#F8F8F2' } },
      { scope: 'constant.numeric', settings: { foreground: '#AE81FF' } },
    ],
  },
  'solarized-dark': {
    name: 'Solarized Dark',
    type: 'dark',
    colors: {
      'editor.background': '#002b36',
      'editor.foreground': '#839496',
      'sideBar.background': '#00212b',
      'sideBar.border': '#004052',
      'editorGroupHeader.tabsBackground': '#00212b',
      'tab.activeBackground': '#002b36',
      'focusBorder': '#268bd2',
      'button.background': '#268bd2',
      'descriptionForeground': '#586e75',
    },
    tokenColors: [
      { scope: 'comment', settings: { foreground: '#586e75', fontStyle: 'italic' } },
      { scope: 'string', settings: { foreground: '#2aa198' } },
      { scope: 'keyword', settings: { foreground: '#859900' } },
      { scope: 'entity.name.function', settings: { foreground: '#268bd2' } },
      { scope: 'entity.name.type', settings: { foreground: '#b58900' } },
    ],
  },
  'solarized-light': {
    name: 'Solarized Light',
    type: 'light',
    colors: {
      'editor.background': '#fdf6e3',
      'editor.foreground': '#586e75',
      'sideBar.background': '#eee8d5',
      'sideBar.border': '#93a1a1',
      'editorGroupHeader.tabsBackground': '#eee8d5',
      'tab.activeBackground': '#fdf6e3',
      'focusBorder': '#268bd2',
      'button.background': '#268bd2',
      'descriptionForeground': '#839496',
    },
    tokenColors: [
      { scope: 'comment', settings: { foreground: '#93a1a1', fontStyle: 'italic' } },
      { scope: 'string', settings: { foreground: '#2aa198' } },
      { scope: 'keyword', settings: { foreground: '#859900' } },
      { scope: 'entity.name.function', settings: { foreground: '#268bd2' } },
    ],
  },
  'one-dark-pro': {
    name: 'One Dark Pro',
    type: 'dark',
    colors: {
      'editor.background': '#282c34',
      'editor.foreground': '#abb2bf',
      'sideBar.background': '#21252b',
      'sideBar.border': '#181a1f',
      'editorGroupHeader.tabsBackground': '#21252b',
      'tab.activeBackground': '#282c34',
      'focusBorder': '#61afef',
      'button.background': '#61afef',
      'descriptionForeground': '#5c6370',
    },
    tokenColors: [
      { scope: 'comment', settings: { foreground: '#5c6370', fontStyle: 'italic' } },
      { scope: 'string', settings: { foreground: '#98c379' } },
      { scope: 'keyword', settings: { foreground: '#c678dd' } },
      { scope: 'entity.name.function', settings: { foreground: '#61afef' } },
      { scope: 'entity.name.type', settings: { foreground: '#e5c07b' } },
    ],
  },
  'github-dark': {
    name: 'GitHub Dark',
    type: 'dark',
    colors: {
      'editor.background': '#0d1117',
      'editor.foreground': '#e6edf3',
      'sideBar.background': '#010409',
      'sideBar.border': '#21262d',
      'editorGroupHeader.tabsBackground': '#010409',
      'tab.activeBackground': '#0d1117',
      'focusBorder': '#1f6feb',
      'button.background': '#238636',
      'descriptionForeground': '#7d8590',
    },
    tokenColors: [
      { scope: 'comment', settings: { foreground: '#8b949e' } },
      { scope: 'string', settings: { foreground: '#a5d6ff' } },
      { scope: 'keyword', settings: { foreground: '#ff7b72' } },
      { scope: 'entity.name.function', settings: { foreground: '#d2a8ff' } },
      { scope: 'entity.name.type', settings: { foreground: '#ffa657' } },
    ],
  },
}

export function getBuiltinRaw(id: string): VsCodeThemeRaw | undefined {
  return BUILTIN_RAW[id]
}
